import { audit, formatDiagnosis, SystemElement } from 'prune-systems';

const elements: SystemElement[] = [
  {
    name: 'ColorPrimary',
    type: 'core',
    description: 'Primary brand colour token used across all components.',
    dependencies: [],
    dependents: ['ButtonBase', 'TypographyScale', 'IconWrapper'],
    lastModified: '2026-03-22',
    linesOfCode: 4,
    complexity: 0,
  },
  {
    name: 'ColorSecondary',
    type: 'core',
    description: 'Secondary brand colour token for accents and highlights.',
    dependencies: [],
    dependents: ['ButtonBase', 'TypographyScale'],
    lastModified: '2026-03-22',
    linesOfCode: 4,
    complexity: 0,
  },
  {
    name: 'ColorTertiary',
    type: 'token',
    description: 'Tertiary colour token, rarely referenced.',
    dependencies: [],
    dependents: ['ButtonOutlineAlt'],
    lastModified: '2025-08-10',
    linesOfCode: 4,
    complexity: 0,
  },
  {
    name: 'OldBrandRed',
    type: 'token',
    description: 'Deprecated brand red from the 2023 palette refresh.',
    dependencies: [],
    dependents: [],
    lastModified: '2023-12-01',
    linesOfCode: 3,
    complexity: 0,
  },
  {
    name: 'SpacingBase',
    type: 'core',
    description: 'Base spacing unit (8px) used by the layout grid.',
    dependencies: [],
    dependents: ['ButtonBase', 'TypographyScale', 'IconWrapper', 'ButtonOutlineAlt'],
    lastModified: '2026-03-18',
    linesOfCode: 6,
    complexity: 0,
  },
  {
    name: 'SpacingLegacy',
    type: 'token',
    description: 'Legacy 6px spacing — copy of the old grid system.',
    dependencies: [],
    dependents: ['IconWrapper'],
    lastModified: '2024-05-20',
    linesOfCode: 5,
    complexity: 0,
    metadata: { similarTo: 'SpacingBase' },
  },
  {
    name: 'ButtonBase',
    type: 'component',
    description: 'Base button component consumed by all button variants.',
    dependencies: ['ColorPrimary', 'ColorSecondary', 'SpacingBase'],
    dependents: ['ButtonOutlineAlt', 'App', 'SettingsPage'],
    lastModified: '2026-03-20',
    linesOfCode: 85,
    complexity: 5,
  },
  {
    name: 'ButtonOutlineAlt',
    type: 'decorator',
    description: 'Outline button variant with minimal overrides.',
    dependencies: ['ButtonBase', 'ColorTertiary', 'SpacingBase'],
    dependents: [],
    lastModified: '2025-10-14',
    linesOfCode: 9,
    complexity: 1,
  },
  {
    name: 'IconWrapper',
    type: 'wrapper',
    description: 'Wraps SVG icons with sizing and colour props.',
    dependencies: ['ColorPrimary', 'SpacingBase', 'SpacingLegacy', 'SVGLib', 'SizeUtil', 'ThemeCtx'],
    dependents: ['ButtonBase'],
    lastModified: '2026-03-15',
    linesOfCode: 130,
    complexity: 17,
  },
  {
    name: 'TypographyScale',
    type: 'core',
    description: 'Type scale tokens (font sizes, line heights, weights).',
    dependencies: ['ColorPrimary', 'ColorSecondary'],
    dependents: ['App', 'DashboardLayout', 'SettingsPage'],
    lastModified: '2026-03-22',
    linesOfCode: 42,
    complexity: 2,
  },
];

const result = audit({
  system: 'Design System',
  elements,
  mode: 'design',
});

console.log(formatDiagnosis(result));
