import { audit, formatDiagnosis, SystemElement } from 'prune-systems';

const elements: SystemElement[] = [
  {
    name: 'Checkout',
    type: 'core',
    description: 'Clones the repository at the specified ref.',
    dependencies: [],
    dependents: ['Install', 'LintAll', 'LintChanged'],
    lastModified: '2026-03-25',
    linesOfCode: 30,
    complexity: 2,
  },
  {
    name: 'Install',
    type: 'entry',
    description: 'Installs project dependencies via npm ci.',
    dependencies: ['Checkout'],
    dependents: ['LintAll', 'LintChanged', 'BuildDev', 'BuildProd'],
    lastModified: '2026-03-25',
    linesOfCode: 25,
    complexity: 1,
  },
  {
    name: 'LintAll',
    type: 'step',
    description: 'Runs eslint across the entire codebase.',
    dependencies: ['Checkout', 'Install'],
    dependents: [],
    lastModified: '2025-09-14',
    linesOfCode: 18,
    complexity: 2,
  },
  {
    name: 'LintChanged',
    type: 'step',
    description: 'Runs eslint only on changed files — duplicate of LintAll with narrower scope.',
    dependencies: ['Checkout', 'Install'],
    dependents: ['BuildProd'],
    lastModified: '2026-03-20',
    linesOfCode: 22,
    complexity: 3,
    metadata: { similarTo: 'LintAll' },
  },
  {
    name: 'BuildDev',
    type: 'wrapper',
    description: 'Development build — thin wrapper around the build script.',
    dependencies: ['Install'],
    dependents: [],
    lastModified: '2025-11-05',
    linesOfCode: 6,
    complexity: 1,
  },
  {
    name: 'BuildProd',
    type: 'step',
    description: 'Production build with minification and tree-shaking.',
    dependencies: ['Install', 'LintChanged'],
    dependents: ['Deploy'],
    lastModified: '2026-03-24',
    linesOfCode: 45,
    complexity: 5,
  },
  {
    name: 'Deploy',
    type: 'step',
    description: 'Deploys the production build to the CDN.',
    dependencies: ['BuildProd'],
    dependents: ['NotifySlack'],
    lastModified: '2026-03-24',
    linesOfCode: 60,
    complexity: 4,
  },
  {
    name: 'NotifySlack',
    type: 'helper',
    description: 'Posts deployment status to Slack.',
    dependencies: ['Deploy', 'SlackSDK', 'ConfigLoader', 'Logger', 'Formatter', 'RetryUtil'],
    dependents: [],
    lastModified: '2026-03-20',
    linesOfCode: 150,
    complexity: 18,
  },
];

const result = audit({
  system: 'CI/CD Pipeline',
  elements,
  mode: 'simplify',
});

console.log(formatDiagnosis(result));
